#! /bin/sh

# import colours from pywal
. "$HOME/.cache/wal/colors.sh"

# bspwm specific config

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          10
bspc config normal_border_color "$color0"
bspc config focused_border_color "$color1"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# auto start stuff

sxhkd &
feh --bg-fill ~/Pictures/gris.png
picom --config ~/.config/picom/picom.conf &
. "$HOME/.config/lemonbar/bar.sh" &
