#! /bin/sh

wal -a "90" -i ~/Pictures/wallpapers/pixel.jpg
. "$HOME/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         5
bspc config window_gap           10
bspc config normal_border_color  "$color0"
bspc config focused_border_color "$color1"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

kitty &
picom &
. "$HOME/.config/lemonbar/bar.sh" &
. "$HOME/.config/dunst/launch.sh" &
